FROM node:lts
# FFmpeg 설치
RUN apt-get update && \
    apt-get install -y ffmpeg && \
    apt-get clean

WORKDIR /usr/src/app

# pnpm 설치
RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN rm -rf node_modules

RUN pnpm install

COPY . .